name: Node-RED CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Configurar Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Construir imagen Docker de Node-RED
      run: docker build -t node-red-app .

    - name: Ejecutar contenedor Node-RED
      run: docker run -d -p 1880:1880 --name node-red-app node-red-app

    - name: Verificar Node-RED
      run: docker exec node-red-app node-red --version
